[theme]
# Primary accent color for interactive elements.
primaryColor = "#379777"

# Background color for the main content area.
backgroundColor = "#ffffff"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#ffefad"

# Color used for almost all text.
textColor = "#000000"

[client]
toolbarMode = "minimal"